"use client";

import { useEffect, useState } from "react";
import Link from "next/link";

type ShowcaseItem = {
  id: string; type: string; title: string; subtitle?: string;
  mediaUrl: string; thumbnailUrl?: string; badge?: string; category: string;
};

export function MediaShowcase() {
  const [items, setItems] = useState<ShowcaseItem[]>([]);
  const [activeVideo, setActiveVideo] = useState(0);

  useEffect(() => {
    fetch("/api/showcase?category=hero").then((r) => r.json()).then((d) => setItems(d.items || []));
  }, []);

  const videos = items.filter((i) => i.type === "video");
  const current = videos[activeVideo];

  return (
    <section className="relative border-t border-white/5 py-20">
      <div className="mx-auto max-w-7xl px-6">
        <div className="text-center">
          <span className="rounded-full border border-orange-500/30 bg-orange-500/10 px-4 py-1.5 text-xs font-medium text-orange-400">LIVE CREATIONS</span>
          <h2 className="mt-4 text-4xl font-bold md:text-5xl">See what Bodana builds.<br /><span className="text-neutral-500">In real time.</span></h2>
        </div>

        <div className="mt-12 grid gap-6 lg:grid-cols-2">
          <div className="relative overflow-hidden rounded-3xl border border-white/10 bg-black shadow-2xl shadow-orange-500/10">
            {current ? (
              <video
                key={current.id}
                src={current.mediaUrl}
                poster={current.thumbnailUrl}
                autoPlay muted loop playsInline
                className="aspect-[9/16] w-full object-cover lg:aspect-video"
              />
            ) : (
              <div className="flex aspect-video items-center justify-center bg-neutral-900">
                <span className="text-neutral-600">Loading showcase...</span>
              </div>
            )}
            <div className="absolute bottom-0 inset-x-0 bg-gradient-to-t from-black/90 to-transparent p-6">
              {current?.badge && <span className="text-xs font-medium text-orange-400">{current.badge}</span>}
              <h3 className="text-xl font-bold">{current?.title}</h3>
              <p className="text-sm text-neutral-400">{current?.subtitle}</p>
            </div>
          </div>

          <div className="grid grid-cols-2 gap-3">
            {videos.map((v, i) => (
              <button
                key={v.id}
                onClick={() => setActiveVideo(i)}
                className={`group relative overflow-hidden rounded-2xl border transition ${activeVideo === i ? "border-orange-500 ring-2 ring-orange-500/30" : "border-white/10 hover:border-white/20"}`}
              >
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img src={v.thumbnailUrl || v.mediaUrl} alt={v.title} className="aspect-video w-full object-cover transition group-hover:scale-105" />
                <div className="absolute inset-0 flex items-center justify-center bg-black/30 opacity-0 transition group-hover:opacity-100">
                  <span className="rounded-full bg-white/20 px-3 py-1 text-xs backdrop-blur">▶ Play</span>
                </div>
                <p className="absolute bottom-2 left-2 text-xs font-medium">{v.title}</p>
              </button>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}

export function AdGallery() {
  const [items, setItems] = useState<ShowcaseItem[]>([]);

  useEffect(() => {
    fetch("/api/showcase").then((r) => r.json()).then((d) => {
      setItems((d.items || []).filter((i: ShowcaseItem) => i.category === "gallery" || i.category === "ad"));
    });
  }, []);

  return (
    <section className="border-t border-white/5 bg-[#0a0a0a] py-20">
      <div className="mx-auto max-w-7xl px-6">
        <h2 className="text-3xl font-bold">Client-ready ads & creatives</h2>
        <p className="mt-2 text-neutral-500">Every asset below was generated by Bodana AI — yours in minutes.</p>
        <div className="mt-10 columns-2 gap-4 md:columns-3 lg:columns-4">
          {items.map((item) => (
            <div key={item.id} className="mb-4 break-inside-avoid overflow-hidden rounded-2xl border border-white/10 bg-white/[0.02] transition hover:border-orange-500/30 hover:shadow-lg hover:shadow-orange-500/10">
              {item.type === "video" ? (
                <video src={item.mediaUrl} poster={item.thumbnailUrl} muted loop playsInline autoPlay className="w-full" />
              ) : (
                /* eslint-disable-next-line @next/next/no-img-element */
                <img src={item.mediaUrl} alt={item.title} className="w-full" />
              )}
              <div className="p-3">
                {item.badge && <span className="text-[10px] text-orange-400">{item.badge}</span>}
                <p className="text-sm font-medium">{item.title}</p>
                <p className="text-xs text-neutral-600">{item.subtitle}</p>
              </div>
            </div>
          ))}
        </div>
        <div className="mt-10 text-center">
          <Link href="/gallery" className="inline-block rounded-full border border-white/20 px-8 py-3 text-sm font-semibold hover:bg-white/5">
            View Full Gallery →
          </Link>
        </div>
      </div>
    </section>
  );
}

export function TestimonialsSection() {
  const [items, setItems] = useState<ShowcaseItem[]>([]);

  useEffect(() => {
    fetch("/api/showcase?category=testimonial").then((r) => r.json()).then((d) => setItems(d.items || []));
  }, []);

  return (
    <section className="py-20">
      <div className="mx-auto max-w-7xl px-6">
        <h2 className="text-center text-3xl font-bold">Trusted by 180,000+ creators</h2>
        <div className="mt-12 grid gap-6 md:grid-cols-3">
          {items.map((t) => (
            <div key={t.id} className="rounded-2xl border border-white/10 bg-gradient-to-b from-white/[0.04] to-transparent p-6">
              <div className="flex items-center gap-3">
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img src={t.mediaUrl} alt={t.title} className="h-12 w-12 rounded-full object-cover ring-2 ring-orange-500/30" />
                <div>
                  <p className="font-semibold">{t.title}</p>
                  <div className="flex text-yellow-400 text-xs">★★★★★</div>
                </div>
              </div>
              <p className="mt-4 text-sm leading-relaxed text-neutral-400">{t.subtitle}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

export function StatsTicker() {
  const stats = [
    { value: "180K+", label: "Creators" },
    { value: "94", label: "AI Tools" },
    { value: "12M+", label: "Creations" },
    { value: "₹50Cr+", label: "Client Revenue" },
    { value: "4.9★", label: "Rating" },
  ];

  return (
    <div className="overflow-hidden border-y border-white/5 bg-gradient-to-r from-orange-500/5 via-purple-500/5 to-orange-500/5 py-4">
      <div className="animate-marquee flex gap-12 whitespace-nowrap">
        {[...stats, ...stats].map((s, i) => (
          <span key={i} className="flex items-center gap-2 text-sm">
            <span className="font-bold text-orange-400">{s.value}</span>
            <span className="text-neutral-500">{s.label}</span>
            <span className="text-neutral-700">·</span>
          </span>
        ))}
      </div>
    </div>
  );
}

export function StickyCTA() {
  return (
    <div className="fixed bottom-0 inset-x-0 z-40 border-t border-orange-500/20 bg-[#050505]/95 backdrop-blur-xl md:hidden">
      <div className="flex items-center justify-between px-4 py-3">
        <div>
          <p className="text-xs font-bold text-orange-400">🔥 LAUNCH OFFER</p>
          <p className="text-[10px] text-neutral-500">50% off with WELCOME50</p>
        </div>
        <Link href="/pricing" className="rounded-full bg-gradient-to-r from-orange-500 to-purple-600 px-5 py-2.5 text-xs font-bold">
          Get Pro ₹499/mo
        </Link>
      </div>
    </div>
  );
}

export function UrgencyBanner() {
  return (
    <div className="border-b border-orange-500/20 bg-gradient-to-r from-orange-500/10 to-purple-600/10 py-2.5 text-center text-sm">
      <span className="text-orange-300">🚀 Limited Launch Offer:</span>{" "}
      <span className="font-semibold">50% OFF</span> first month with code{" "}
      <code className="rounded bg-white/10 px-2 py-0.5 font-mono text-orange-400">WELCOME50</code>
      {" · "}
      <Link href="/pricing" className="font-semibold text-white underline">Claim Now →</Link>
    </div>
  );
}
